[package]
name = "redscript"
version = "0.1.0"
authors = ["jac3km4 <jac3km4@pm.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
byteorder = "1.4"
modular-bitfield = "0.11"
crc32fast = "1.2"
strum = { version = "0.20", features = ["derive"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
